/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alpha_healthmobile_uninstall_UninstallApp */

#ifndef _Included_com_alpha_healthmobile_uninstall_UninstallApp
#define _Included_com_alpha_healthmobile_uninstall_UninstallApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alpha_healthmobile_uninstall_UninstallApp
 * Method:    Uninstall
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alpha_healthmobile_uninstall_UninstallApp_Uninstall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
